---
before_script:
  - "cd Server"
os: windows
dotnet: 5.0
language: csharp
mono: none
install:
  - choco install iisexpress
script:
  - dotnet restore
  - dotnet build
  - cmd.exe //c "RefreshEnv.cmd"
  - StartServer.bat
  - dotnet test ../ServerTests/ServerTests.csproj
